# Generated by Django 5.1 on 2024-08-28 11:12

import people.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StarWarsCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('height', models.IntegerField(null=True)),
                ('mass', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('hair_color', models.CharField(max_length=50)),
                ('skin_color', models.CharField(max_length=50)),
                ('eye_color', models.CharField(max_length=50)),
                ('birth_year', models.DecimalField(decimal_places=1, max_digits=6, null=True)),
                ('gender', models.CharField(choices=[('male', 'Reef'), ('female', 'Wall'), ('n/a', 'n/a')], max_length=30)),
                ('home_world_name', models.CharField(db_index=True, max_length=50)),
                ('image', models.ImageField(default='people/default.jpg', upload_to=people.models.generate_filename, verbose_name='Character Image')),
            ],
        ),
    ]
