# Generated by Django 5.1 on 2024-08-30 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='starwarscharacter',
            name='gender',
            field=models.CharField(choices=[('male', 'male'), ('female', 'female'), ('n/a', 'n/a')], max_length=30),
        ),
    ]
